version: "3.7"
services:
  openssh-server:
    image: limingxinleo/openssh-server
    build:
      context: "."
    volumes:
      - ./authorized_keys:/root/.ssh/authorized_keys
    ports:
      - "2222:22"
    restart: always
    networks:
      - default-network
networks:
  default-network:
    external: true
